"""
SQLAlchemy ORM models for DONS platform.
"""
from sqlalchemy import Column, String, Integer, DateTime, Text, ForeignKey, JSON, Boolean, Float
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from database import Base
import uuid


def new_uuid():
    """Generate a new UUID string."""
    return str(uuid.uuid4())


class User(Base):
    """User model for authentication and tracking."""
    __tablename__ = "users"
    
    id = Column(String(36), primary_key=True, default=new_uuid)
    email = Column(String(255), unique=True, nullable=False, index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    last_login = Column(DateTime(timezone=True))
    
    # Relationships
    infrastructure_uploads = relationship("InfrastructureUpload", back_populates="user", cascade="all, delete-orphan")


class InfrastructureUpload(Base):
    """Infrastructure upload tracking."""
    __tablename__ = "infrastructure_uploads"
    
    id = Column(String(36), primary_key=True, default=new_uuid)
    user_id = Column(String(36), ForeignKey("users.id", ondelete="CASCADE"), nullable=True, index=True)
    filename = Column(String(255), nullable=False)
    file_size_bytes = Column(Integer, nullable=False)
    file_type = Column(String(50), nullable=False)  # .tf, .tf.json, .yaml, .json, .tfstate
    storage_url = Column(Text, nullable=False)  # URL in DigitalOcean Spaces
    parsed_resources = Column(JSON)  # Parsed AWS resources
    parse_status = Column(String(50), default="pending")  # pending, completed, failed
    parse_errors = Column(Text)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), index=True)
    
    # Relationships
    user = relationship("User", back_populates="infrastructure_uploads")
    migration_plans = relationship("MigrationPlan", back_populates="infrastructure_upload", cascade="all, delete-orphan")


class MigrationPlan(Base):
    """Migration plan generated by Cloud Migration Architect agent."""
    __tablename__ = "migration_plans"
    
    id = Column(String(36), primary_key=True, default=new_uuid)
    upload_id = Column(String(36), ForeignKey("infrastructure_uploads.id", ondelete="CASCADE"), nullable=False, index=True)
    resources_detected = Column(JSON, nullable=False)  # List of detected AWS resources
    resource_mappings = Column(JSON, nullable=False)  # AWS to DO mappings
    migration_plan = Column(JSON, nullable=False)  # Deployment steps, dependencies
    risk_analysis = Column(JSON, nullable=False)  # Risk assessment
    overall_risk_score = Column(String(20), nullable=False, index=True)  # Low, Medium, High
    estimated_duration_hours = Column(Integer)
    terraform_code = Column(Text)  # Generated DO Terraform code
    terraform_file_url = Column(Text)  # URL in Spaces
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    # Relationships
    infrastructure_upload = relationship("InfrastructureUpload", back_populates="migration_plans")
    deployments = relationship("Deployment", back_populates="migration_plan", cascade="all, delete-orphan")
    ai_recommendations = relationship("AIRecommendation", back_populates="migration_plan", cascade="all, delete-orphan")


class Deployment(Base):
    """Deployment tracking for infrastructure deployed to DigitalOcean."""
    __tablename__ = "deployments"
    
    id = Column(String(36), primary_key=True, default=new_uuid)
    migration_plan_id = Column(String(36), ForeignKey("migration_plans.id", ondelete="CASCADE"), nullable=False, index=True)
    status = Column(String(50), default="pending")  # pending, in_progress, completed, failed
    deployed_resources = Column(JSON)  # List of deployed resources with IDs
    failed_resource = Column(String(255))
    error_message = Column(Text)
    progress_percent = Column(Integer, default=0)
    started_at = Column(DateTime(timezone=True))
    completed_at = Column(DateTime(timezone=True))
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    # Relationships
    migration_plan = relationship("MigrationPlan", back_populates="deployments")
    alerts = relationship("Alert", back_populates="deployment", cascade="all, delete-orphan")
    self_healing_actions = relationship("SelfHealingAction", back_populates="deployment", cascade="all, delete-orphan")


class Alert(Base):
    """Monitoring alerts generated by DevOps agent."""
    __tablename__ = "alerts"
    
    id = Column(String(36), primary_key=True, default=new_uuid)
    deployment_id = Column(String(36), ForeignKey("deployments.id", ondelete="CASCADE"), index=True)
    resource_id = Column(String(255), nullable=False, index=True)  # DO resource ID
    timestamp = Column(DateTime(timezone=True), server_default=func.now(), index=True)
    severity = Column(String(20), nullable=False, index=True)  # Low, Medium, High
    message = Column(Text, nullable=False)
    metric_type = Column(String(50), nullable=False)  # cpu, storage, network, etc.
    metric_value = Column(Float, nullable=False)
    acknowledged = Column(Boolean, default=False)
    
    # Relationships
    deployment = relationship("Deployment", back_populates="alerts")
    self_healing_actions = relationship("SelfHealingAction", back_populates="alert", cascade="all, delete-orphan")


class SelfHealingAction(Base):
    """Self-healing actions taken by DevOps agent."""
    __tablename__ = "self_healing_actions"
    
    id = Column(String(36), primary_key=True, default=new_uuid)
    alert_id = Column(String(36), ForeignKey("alerts.id", ondelete="CASCADE"), nullable=False, index=True)
    deployment_id = Column(String(36), ForeignKey("deployments.id", ondelete="CASCADE"), nullable=False, index=True)
    resource_id = Column(String(255), nullable=False)
    action_type = Column(String(100), nullable=False)  # storage_autoscaling, resource_resize, etc.
    terraform_code = Column(Text, nullable=False)  # Generated Terraform fix
    pr_url = Column(Text)  # GitHub PR URL
    pr_status = Column(String(50), default="pending")  # pending, open, merged, closed
    status = Column(String(50), default="pending")  # pending, applied, failed
    error_message = Column(Text)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), index=True)
    applied_at = Column(DateTime(timezone=True))
    
    # Relationships
    alert = relationship("Alert", back_populates="self_healing_actions")
    deployment = relationship("Deployment", back_populates="self_healing_actions")


class AIRecommendation(Base):
    """AI recommendations generated by AI Enablement agent."""
    __tablename__ = "ai_recommendations"
    
    id = Column(String(36), primary_key=True, default=new_uuid)
    migration_plan_id = Column(String(36), ForeignKey("migration_plans.id", ondelete="CASCADE"), nullable=False, index=True)
    capability_name = Column(String(255), nullable=False)
    description = Column(Text, nullable=False)
    do_service = Column(String(100), nullable=False)  # Gradient AI, GPU Droplets, DOKS, etc.
    implementation_effort = Column(String(20), nullable=False)  # Low, Medium, High
    business_value = Column(String(20), nullable=False)  # Low, Medium, High
    code_example = Column(Text)
    estimated_cost_monthly = Column(Float)
    rag_architecture = Column(JSON)  # RAG architecture details with OpenSearch
    vector_embedding_strategy = Column(JSON)  # Vector embedding details
    opensearch_cluster_config = Column(JSON)  # OpenSearch cluster sizing
    priority = Column(Integer, default=0)  # Higher = more important
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    # Relationships
    migration_plan = relationship("MigrationPlan", back_populates="ai_recommendations")


class Document(Base):
    """Uploaded document for Store Intelligence."""
    __tablename__ = "documents"

    id = Column(String(36), primary_key=True, default=new_uuid)
    filename = Column(String(255), nullable=False)
    file_type = Column(String(20), nullable=False)  # pdf, txt, md, csv
    file_size_bytes = Column(Integer, nullable=False)
    storage_url = Column(Text, nullable=False)  # Spaces URL
    chunk_count = Column(Integer, default=0)
    processing_status = Column(String(50), default="pending")  # pending, processing, completed, failed
    error_message = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    # Relationships
    chunks = relationship("DocumentChunk", back_populates="document", cascade="all, delete-orphan")


class DocumentChunk(Base):
    """Document chunk for vector embedding."""
    __tablename__ = "document_chunks"

    id = Column(String(36), primary_key=True, default=new_uuid)
    document_id = Column(String(36), ForeignKey("documents.id", ondelete="CASCADE"), nullable=False, index=True)
    chunk_index = Column(Integer, nullable=False)
    content = Column(Text, nullable=False)
    token_count = Column(Integer, nullable=False)
    embedding_id = Column(String(255), nullable=True)  # OpenSearch document ID
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # Relationships
    document = relationship("Document", back_populates="chunks")
