"""Migration summary page displaying analysis, costs, and migration plan."""

import streamlit as st
import plotly.graph_objects as go
from components.agent_activity import log_activity
from components.sidebar import navigate_to


def render_summary(client):
    """Render the migration summary page."""
    st.markdown(
        '<div style="background:#1a1a2e;padding:1rem 1.5rem;border-radius:10px;border-left:4px solid #0080FF;margin-bottom:1rem;">'
        '<p style="font-size:1.5rem;margin:0;color:#fff;">🏗️ Migration Architect</p>'
        '<p style="font-size:0.9rem;color:#aaa;margin:0.3rem 0 0 0;">Analyzes infrastructure, generates migration plans with risk analysis and cost comparison</p>'
        '</div>',
        unsafe_allow_html=True,
    )
    st.header("📊 Migration Summary")

    upload_id = st.session_state.get("upload_id")
    if not upload_id:
        st.warning("⚠️ Please upload an infrastructure file first.")
        if st.button("← Go to Upload"):
            navigate_to("migration", "📁 Upload")
            st.rerun()
        return

    # Fetch data if not cached
    if not st.session_state.get("analysis_result"):
        _fetch_all_data(client, upload_id)

    analysis = st.session_state.get("analysis_result")
    plan = st.session_state.get("escape_plan")
    costs = st.session_state.get("cost_result")

    if not analysis and not plan and not costs:
        st.error("Failed to fetch migration data. Please try again.")
        return

    if costs:
        _render_cost_metrics(costs)
        st.markdown("---")
        _render_cost_chart(costs)

    if analysis:
        st.markdown("---")
        _render_resources_table(analysis)

    if plan:
        st.markdown("---")
        _render_migration_plan(plan)

    # Navigation links between steps
    st.markdown("---")
    col1, col2 = st.columns([1, 1])
    with col1:
        if st.button("← Back to Upload"):
            navigate_to("migration", "📁 Upload")
            st.rerun()
    with col2:
        if st.session_state.get("plan_id"):
            if st.button("Next → Deployment", type="primary"):
                navigate_to("migration", "🚀 Infrastructure Deployment")
                st.rerun()


    st.caption("Generated by Migration Architect Agent using Gradient AI llama3-8b-instruct")


def _fetch_all_data(client, upload_id):
    """Fetch analysis, escape plan, and cost data from API."""
    with st.spinner("Analyzing infrastructure..."):
        success, data = client.analyze(upload_id)
        if success:
            st.session_state.analysis_result = data
            log_activity("migration_architect", "Analyzed infrastructure", f"{data.get('resources_detected', 0)} resources")
        else:
            st.error(f"Analysis failed: {data}")

    with st.spinner("Generating migration plan..."):
        success, data = client.generate_escape_plan(upload_id)
        if success:
            st.session_state.escape_plan = data
            st.session_state.plan_id = data.get("plan_id")
            log_activity("migration_architect", "Generated migration plan")
        else:
            st.error(f"Migration plan generation failed: {data}")

    with st.spinner("Calculating costs..."):
        success, data = client.calculate_costs(upload_id)
        if success:
            st.session_state.cost_result = data
            savings = data.get("savings_percentage", 0)
            log_activity("migration_architect", "Calculated costs", f"{savings:.1f}% savings")
        else:
            st.error(f"Cost calculation failed: {data}")


def _render_cost_metrics(costs):
    """Render cost comparison metric cards."""
    aws_cost = costs.get("aws_monthly_cost", 0)
    do_cost = costs.get("do_monthly_cost", 0)
    savings = costs.get("monthly_savings", 0)
    savings_pct = costs.get("savings_percentage", 0)

    if savings_pct >= 30:
        risk_level = "Low"
    elif savings_pct >= 15:
        risk_level = "Medium"
    else:
        risk_level = "High"

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("AWS Monthly Cost", f"${aws_cost:,.2f}")
    col2.metric("DO Monthly Cost", f"${do_cost:,.2f}")
    col3.metric("Monthly Savings", f"${savings:,.2f}", delta=f"{savings_pct:.1f}%")
    col4.metric("Risk Level", risk_level)


def _render_cost_chart(costs):
    """Render grouped bar chart comparing AWS vs DO costs by category."""
    st.subheader("Cost Comparison by Category")

    aws_bd = costs.get("aws_breakdown", {})
    do_bd = costs.get("do_breakdown", {})

    categories = ["Compute", "Storage", "Network", "Database", "Kubernetes", "Load Balancer"]
    keys = ["compute", "storage", "network", "database", "kubernetes", "load_balancer"]

    aws_values = [aws_bd.get(k, 0) for k in keys]
    do_values = [do_bd.get(k, 0) for k in keys]

    fig = go.Figure(data=[
        go.Bar(name="AWS", x=categories, y=aws_values, marker_color="#FF9900"),
        go.Bar(name="DigitalOcean", x=categories, y=do_values, marker_color="#0080FF"),
    ])
    fig.update_layout(
        barmode="group",
        yaxis_title="Monthly Cost (USD)",
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        height=400,
    )
    st.plotly_chart(fig, width="stretch")


def _render_resources_table(analysis):
    """Render detected resources table."""
    st.subheader("Detected Resources")

    resources = analysis.get("resources", [])
    if not resources:
        st.info("No resources detected.")
        return

    table_data = []
    for r in resources:
        table_data.append({
            "Name": r.get("name", "N/A"),
            "AWS Type": r.get("type", "N/A"),
            "Configuration": str(r.get("config", {}))[:100],
        })

    st.dataframe(table_data, width="stretch")


def _render_migration_plan(plan):
    """Render migration plan with expandable sections."""
    st.subheader("Migration Plan")

    steps = plan.get("deployment_steps", [])
    if steps:
        with st.expander("📋 Deployment Steps", expanded=True):
            for step in steps:
                st.markdown(f"**Step {step.get('step', '')}: {step.get('title', '')}**")
                st.markdown(step.get("description", ""))
                dur = step.get("estimated_duration", "")
                if dur:
                    st.caption(f"Estimated duration: {dur}")
                st.markdown("---")

    risks = plan.get("risks", [])
    if risks:
        with st.expander("⚠️ Risk Analysis"):
            for risk in risks:
                severity = risk.get("severity", "Medium")
                icon = {"High": "🔴", "Medium": "🟡", "Low": "🟢"}.get(severity, "⚪")
                st.markdown(f"{icon} **{risk.get('risk', '')}** ({severity})")
                st.markdown(f"Impact: {risk.get('impact', 'N/A')}")
                st.markdown(f"Mitigation: {risk.get('mitigation', 'N/A')}")
                st.markdown("---")

    rollbacks = plan.get("rollback_procedures", [])
    if rollbacks:
        with st.expander("🔄 Rollback Procedures"):
            for rb in rollbacks:
                st.markdown(f"**{rb.get('resource', 'N/A')}**")
                for s in rb.get("steps", []):
                    st.markdown(f"- {s}")
                st.markdown("---")

    duration = plan.get("duration_estimate", {})
    if duration:
        with st.expander("⏱️ Duration Estimate"):
            st.markdown(f"**Total estimated duration:** {duration.get('formatted', 'N/A')}")
